#!/usr/bin/env python

#############################################################################
# ParaMark: A Benchmark for Parallel/Distributed Systems
# Copyright (C) 2009,2010  Nan Dun <dunnan@yl.is.s.u-tokyo.ac.jp>
# Distributed under GNU General Public Licence version 3
#############################################################################

#
# paramark
# Main Routines
#

import sys
import optparse

def main(argv):
    parse_argv(argv)
    
    return 0

def parse_argv(argv):
    usage = "paramark [options]"
    optParser = optparse.OptionParser(usage=usage)

    optParser.remove_option("-h")
    optParser.add_option("-h", "--help", action="store", 
        type="string", dest="helpOf", metavar="fs", default="",
        help="print help for specific benchmarks")

    optParser.add_option("-m", "--mode"
    
    opts, args = optParser.parse_args(argv)
    
    # Nothing specified, print help
    if len(argv) == 1 and args[0] == argv[0]:
        optParser.print_help()


if __name__ == '__main__':
    sys.exit(main(sys.argv))

# EOF
