#!/usr/bin/env python

#############################################################################
# ParaMark: A Parallel/Distributed File Systems Benchmark
# Copyright (C) 2009,2010  Nan Dun <dunnan@yl.is.s.u-tokyo.ac.jp>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

#
# paramark
# Main Routines
#

import sys

# ParaMark modules
import fsbench

def standalone_main(argv):
    # Get options and configurations
    mybench = fsbench.Bench()
    mybench.load(argv)
    
    mybench.save()

if __name__ == "__main__":
    sys.exit(standalone_main(sys.argv))
